"""create initial tables

Revision ID: 747d2dde69c2
Revises: 
Create Date: 2026-02-15 17:19:46.293749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '747d2dde69c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier (UUID v4)'),
    sa.Column('google_sub', sa.String(length=255), nullable=False, comment="Google OAuth 'sub' claim - unique identifier from Google"),
    sa.Column('email', sa.String(length=320), nullable=False, comment='User email address from Google profile'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='User display name from Google profile'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment="URL to user's Google profile picture"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete flag for account deactivation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last profile update timestamp'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Most recent login timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique document identifier (UUID v4)'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Document owner (creator) foreign key'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional document description'),
    sa.Column('crdt_state', sa.LargeBinary(), nullable=True, comment='Binary CRDT state vector (Y.Doc serialized as Uint8Array)'),
    sa.Column('crdt_version', sa.Integer(), nullable=False, comment='CRDT state version counter for conflict detection'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='Soft-delete flag for document archival'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Public access flag (anyone with link can view)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Document creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp'),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True, comment='Last content edit timestamp (for activity tracking)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_owner_archived', 'documents', ['owner_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index('ix_documents_updated_at', 'documents', ['updated_at'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique login record identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User foreign key'),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Login event timestamp'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent string'),
    sa.Column('country_code', sa.String(length=3), nullable=True, comment='ISO 3166-1 alpha-2 country code from IP geolocation'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='City from IP geolocation'),
    sa.Column('region', sa.String(length=255), nullable=True, comment='Region/state from IP geolocation'),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False, comment='Flag for suspicious login attempts'),
    sa.Column('login_method', sa.String(length=50), nullable=False, comment='Authentication method used'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_ip_address'), 'login_history', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_history_login_at'), 'login_history', ['login_at'], unique=False)
    op.create_index('ix_login_history_suspicious', 'login_history', ['is_suspicious', 'login_at'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index('ix_login_history_user_time', 'login_history', ['user_id', 'login_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique token record identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User foreign key'),
    sa.Column('token_hash', sa.String(length=512), nullable=False, comment='SHA-256 hash of the refresh token (never store plaintext)'),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True, comment='Device/browser fingerprint for session tracking'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent string'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address at token creation'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='Token revocation flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Token creation timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration timestamp'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last token usage timestamp'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Token revocation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'is_revoked', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('document_permissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique permission record identifier'),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='Document foreign key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User foreign key'),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='document_role_enum'), nullable=False, comment='User role for this document'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Permission grant timestamp'),
    sa.Column('granted_by_id', sa.UUID(), nullable=True, comment='User who granted this permission'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_user_permission')
    )
    op.create_index(op.f('ix_document_permissions_document_id'), 'document_permissions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_permissions_user_id'), 'document_permissions', ['user_id'], unique=False)
    op.create_index('ix_permissions_user_role', 'document_permissions', ['user_id', 'role'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique invitation identifier'),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='Document foreign key'),
    sa.Column('invited_by_id', sa.UUID(), nullable=False, comment='User who sent the invitation'),
    sa.Column('invitee_email', sa.String(length=320), nullable=False, comment='Email address of the invitee'),
    sa.Column('invitee_id', sa.UUID(), nullable=True, comment='User ID if invitee already has an account'),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='document_role_enum'), nullable=False, comment='Role to grant upon acceptance'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitation_status_enum'), nullable=False, comment='Current invitation status'),
    sa.Column('token_hash', sa.String(length=512), nullable=False, comment='SHA-256 hash of invitation token for secure link'),
    sa.Column('message', sa.Text(), nullable=True, comment='Optional personal message from inviter'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Invitation creation timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Invitation expiration timestamp'),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True, comment='Invitation response timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_document_id'), 'invitations', ['document_id'], unique=False)
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_invited_by_id'), 'invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_invitations_invitee_email'), 'invitations', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_invitations_invitee_id'), 'invitations', ['invitee_id'], unique=False)
    op.create_index('ix_invitations_pending_expiry', 'invitations', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_index('uq_document_invitee_email_pending', 'invitations', ['document_id', 'invitee_email'], unique=True, postgresql_where="status = 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_invitee_email_pending', table_name='invitations', postgresql_where="status = 'PENDING'")
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index('ix_invitations_pending_expiry', table_name='invitations')
    op.drop_index(op.f('ix_invitations_invitee_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invitee_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invited_by_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_document_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_permissions_user_role', table_name='document_permissions')
    op.drop_index(op.f('ix_document_permissions_user_id'), table_name='document_permissions')
    op.drop_index(op.f('ix_document_permissions_document_id'), table_name='document_permissions')
    op.drop_table('document_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_login_history_user_time', table_name='login_history')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index('ix_login_history_suspicious', table_name='login_history')
    op.drop_index(op.f('ix_login_history_login_at'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_ip_address'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('ix_documents_updated_at', table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index('ix_documents_owner_archived', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
